// <auto-generated />
using System;
using BusinessWorkflowBoard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessWorkflowBoard.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BusinessWorkflowBoard.Models.BusinessTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwningDepartment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestingDepartment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("BusinessWorkflowBoard.Models.BusinessTask", b =>
                {
                    b.OwnsMany("BusinessWorkflowBoard.Models.HandoffEntry", "Handoffs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("BusinessTaskId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("FromDepartment")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ToDepartment")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("BusinessTaskId");

                            b1.ToTable("TaskHandoffs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BusinessTaskId");
                        });

                    b.Navigation("Handoffs");
                });
#pragma warning restore 612, 618
        }
    }
}
